version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
    security-updates-only: true
    open-pull-requests-limit: 10
    labels:
      - "security"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    security-updates-only: true
    open-pull-requests-limit: 10
    labels:
      - "security"